### ISSUE TITLE
Suggestion: different selection background for dark theme

### ISSUE THREAD

**Issue by kriscoleman** [johnpapa/vscode-winteriscoming#11]
Hello, 

I just wanted to make a suggestion is all. I use VSCodeVIM and when I'm in visual mode, I find that the dark theme doesn't have enough contrast when I'm selecting text. It makes it difficult for me to see what text I'm selecting as the selection background color is close to the same color of the document background. 

To fix this, I've created a custom setting for my selection background. I wanted to share it here and suggest that maybe this be put into the theme for everyone to use: 

```
    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#4a84ad"
    }
```

**Comment by johnpapa** [comment]
thanks for the feedback. I was thinking of changing that recently, too. what do you tihnk about

```
    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#004b88"
    }
```

The darker one works better on bth light and dark fonts.
![image](https://user-images.githubusercontent.com/1202528/37546436-383991ce-2943-11e8-8fc2-6d82f9f7abdb.png)

**Comment by johnpapa** [comment]
updated in 0.5.2

**Comment by kriscoleman** [comment]
That looks great! I like that it works with both light and dark themes. Thanks John!
