### ISSUE TITLE
Change color of unused imports

### ISSUE THREAD

**Issue by DuncanFaulkner** [johnpapa/vscode-winteriscoming#19]
### OS and Version?
Ubuntu

### Versions
  16.04

### Repro steps
Add an import statement and include a couple of modules (use one but not the other), the color of the unused imports is hard to see immediately, can this be changed to either a different color or have it as a strike through?

**Comment by johnpapa** [comment]
I'll check into this. Is there a color besides the gray you think would be good?

**Comment by DuncanFaulkner** [comment]
Hi John, 
I think it needs to stand out so something like the color for private variables used in the constructor, the same if the whole import is not used, though that is a little easier to spot. 

![image](https://user-images.githubusercontent.com/1952116/40651235-15380c36-632d-11e8-8a8b-3a3a1647f665.png)

![image](https://user-images.githubusercontent.com/1952116/40651257-29fb8e04-632d-11e8-86d2-b97aeff257ee.png)

**Comment by DuncanFaulkner** [comment]
Hi John
I was going to take a look to see if I could make the changes I asked for purely as an exercise for me to learn a bit more about VS Code and how extensions work. I've forked and clone the project and I have opened it in VS Code. 

How do I run it to see the changes?   

Cheers

**Comment by DuncanFaulkner** [comment]
Hi John,

Are you able to help with this or point me in the right direction? 
Cheers

**Comment by johnpapa** [comment]
I haven't had time to look into this. You may want to explore the theming settings in the vs code docs on line. Then make a PR or we can discuss here.

**Comment by DuncanFaulkner** [comment]
Hi John,
Thanks I will take a look, I see on Twitter you have a lot of work on updating your Pluralsight courses and conferences.

**Comment by johnpapa** [comment]
You can run it by pressing F5 to debug.

**Comment by johnpapa** [comment]
Closing for now. If you feel it should be reopened, please do so with updated information.
