### ISSUE TITLE
Some Colors are very close (maybe colorblind thing?)

### ISSUE THREAD

**Issue by jtsom** [johnpapa/vscode-winteriscoming#2]
Some of the colors are very close, if not indistinguishable. It could be a color blind thing, but in the case below, the colors of the "import" and the items in the { }'s are very close.

(I'd attempt a fix, but "color blind".. :) )

<img width="514" alt="screen shot 2017-10-20 at 9 46 40 am" src="https://user-images.githubusercontent.com/13488/31824042-e79c96fc-b57b-11e7-9321-73add8ef3e2a.png">

Also not sure if "imports" and items in array are different colors, (or are supposed to be?):

<img width="253" alt="screen shot 2017-10-20 at 9 49 29 am" src="https://user-images.githubusercontent.com/13488/31824098-0e5adc7c-b57c-11e7-8274-c5bfec2347b2.png">

**Comment by johnpapa** [comment]
yeah, they are close, but this is intentional. keywords and the symbols are both shades of blue.

I like this ... but I'm open to suggestions.

**Comment by johnpapa** [comment]
im going to close this for now. if you have suggestions, please re-open. I'm open to tweaking the colors if it makes it better.

thanks
