### ISSUE TITLE
JSX bracket improvement

### ISSUE THREAD

**Issue by tomByrer** [johnpapa/vscode-winteriscoming#22]
### OS and Version?
Win10

### Versions
VSCode: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Dark Blue 0.9.0

## JSX Brackets
The HTML/SVG tag delimiters are pure white, hard to tell apart from quoted strings & IMHO too 'loud' of a color to need that much attention.  So I switched it to 'comment gray', & since comments are italic, I feel there won't be much confusion.
#### Before
![theme-winter-before](https://user-images.githubusercontent.com/1308419/55806428-d881ce00-5aa5-11e9-91bd-f4ba52b533aa.JPG)
#### After
```json
      "name": "Punctuation/Brackets/Tags",
      "scope": ["punctuation.definition.block", "punctuation.definition.tag"],
      "settings": {
        "foreground": "#999"
      }
```
![theme-winter-after](https://user-images.githubusercontent.com/1308419/55806595-2e567600-5aa6-11e9-960a-8f5b95632bd9.JPG)

I'm not sure if this gray is the best, or another shade would be better.  In smaller JSX files, it is handy to have brighter tags; my example is extreme.

*Side note:*  The screenshots are actually an `.htm` file that for some reason VSCode is tricked into 'JavaScript mode'.  I'm looking into the issue.

**Comment by johnpapa** [comment]
I'm open to suggestions and PRs :)

**Comment by tomByrer** [comment]
Might be a VSCode issue:
https://github.com/Microsoft/vscode/issues/20488
