### ISSUE TITLE
Dark Theme Gone

### ISSUE THREAD

**Issue by y-spreen** [johnpapa/vscode-winteriscoming#23]
It's been my all-time favorite code theme. I use nothing else. Is there gonna be a replacement, or do I have to find a different theme?

![image](https://user-images.githubusercontent.com/12631527/56863194-b4822000-69b3-11e9-94e5-36772babdcd9.png)

**Comment by deeKay93** [comment]
+1
I also like(d) the dark one.

**Comment by JeffMarvin** [comment]
What was lagging in terms of support, and could I do some work to bring it back?

**Comment by tsummerer** [comment]
+1!

**Comment by ivano9** [comment]
the best theme was removed :man_facepalming: ...

**Comment by sneridagh** [comment]
+1 here too. What does it mean “it was not supported”. Personally I didn’t care much about it... @johnpapa if you worry about that, just write a disclaimer about it and that’s it.

Thanks for the theme and the effort anyways!

**Comment by johnpapa** [comment]
If ya'll like the dark one (not blue) you could create a PR to add it back. It was lagging behind the others. The blue one is almost identical ... just needs blackish background.

**Comment by sneridagh** [comment]
@johnpapa Yesterday I gave the blue a try, and there are quite a few changes in key artifacts that personally I don’t like. Being a big one the greenish strings :) But there is no accounting for tastes, they say!

I can create a PR it this morning, with the 0.9.0 version. Thanks!!

**Comment by johnpapa** [comment]
im not sure the green will stay. you could open an issue on those and we can discuss a color. The existing one wasnt working out so well in some cases.

**Comment by Silvea12** [comment]
+1 on dark theme, I loved it

**Comment by skeetbooth** [comment]
Agreed. Well done @sneridagh!

**Comment by johnpapa** [comment]
coming back in 1.1.0
