### ISSUE TITLE
String colors in dark theme.

### ISSUE THREAD

**Issue by sneridagh** [johnpapa/vscode-winteriscoming#25]
Not using the template, because I'm not reporting any bug.

Due to the removal of the Dark theme in 1.0.0 I give a try to the Dark blue theme. I found it quite pleasant too but it had a no go for me, that in fact I've been running from the themes I use for my IDEs during the last years: The greenish strings in code (in fact, in JSON files are violet-ish). Not really familiar with the VSCode theming, but I noticed that.

<img width="597" alt="image" src="https://user-images.githubusercontent.com/486927/56949566-8cb9c600-6b33-11e9-837a-6857334e0777.png">

<img width="918" alt="image" src="https://user-images.githubusercontent.com/486927/56949668-c8549000-6b33-11e9-9c48-7a7817d262a1.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/486927/56949753-fb971f00-6b33-11e9-9c4c-ae29b32b959c.png">

I guess it's a matter of tastes, don't want to change it, I can live with it (or continue using the Dark theme if we bring it back). Just wanted to start a discussion. I'm not a designer, nor a good color matcher either :) but how about another pastel blue-ish or a pastel violet? :) Maybe the same violet as used in the JSON files strings?

**Comment by johnpapa** [comment]
I have changed the string colors ... let me know if this is better.
![image](https://user-images.githubusercontent.com/1202528/58615472-d7aa3300-82c3-11e9-9599-0ff5a0569ca0.png)

**Comment by johnpapa** [comment]
strings have been changed.

closing for now. if you feel it needs to be reopened, please reopen with updated information.

thanks
