### ISSUE TITLE
The highlighting of the JAVA code

### ISSUE THREAD

**Issue by wjbgis** [johnpapa/vscode-winteriscoming#26]
Thank you for providing such a beautiful theme, I especially like the background color of the dark blue. But I feel that the highlight color of the code is not suitable for JAVA, It makes the Java code less recognizable and affects the programming experience. I will be grateful if you can make some improvements. Thank you again for this set of themes.

**Comment by johnpapa** [comment]
if you have some ideas please share screen shots of what might look better. thanks!

**Comment by johnpapa** [comment]
closing for now. if ideas spring up, please reopen
