### ISSUE TITLE
"No Italics" variation still has italics

### ISSUE THREAD

**Issue by jtsom** [johnpapa/vscode-winteriscoming#27]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
Any

### Versions
  1.0.0

### Repro steps
Choose Winter is Coming (No Italics)

Italics still show, there isn't any difference between the two variations.

**Comment by johnpapa** [comment]
Can you clarify where you see this? I just tried it and here is what i see ...
![2019-05-30_10-13-53](https://user-images.githubusercontent.com/1202528/58615375-97e34b80-82c3-11e9-9ef9-e284b526bb00.gif)

**Comment by jtsom** [comment]
Pretty much anywhere:

![ezgif com-optimize](https://user-images.githubusercontent.com/13488/58625937-812bfd00-82a1-11e9-8cb4-e2b6d36c359d.gif)

**Comment by johnpapa** [comment]
Are you using a font that supports italics? 

The readme points a few out.

**Comment by jtsom** [comment]
My font settings are: Menlo, Monaco, 'Courier New', monospace

Doesn't matter which font I use, I see italics when I select the "no italic" variation. I changed to Fira Code and the italics are there no matter which version is selected.

Fira Code - No Italic variation
<img width="608" alt="image" src="https://user-images.githubusercontent.com/13488/58627462-580d6b80-82a5-11e9-96f0-c98d824cf162.png">

Fira Code - Italic variation
<img width="657" alt="image" src="https://user-images.githubusercontent.com/13488/58627485-63f92d80-82a5-11e9-9c3b-5954f7cf6268.png">

**Comment by johnpapa** [comment]
Not all, but some settings have italics still ... I just found them. I tested and published a fix in 1.1.1.

Thanks for reporting.
