### ISSUE TITLE
*Request* - Italics in light theme

### ISSUE THREAD

**Issue by petepall** [johnpapa/vscode-winteriscoming#29]
> Please provide us with the following information:
> ---------------------------------------------------------------
When using the light theme of the winter is coming theme, there are no italics like we can see in the blue version.
It would be good to have also a light version with the italic characters.

### OS and Version?
> Windows  10. 

### Versions
  > VS code version 1.33.1
  > Winter is coming 1.0.0

### Repro steps
  > Switch to the light theme of Winter is coming 

### The log given by the failure.
> None

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment]
I'd love to get a PR for this. Please consider making one and I'll review

**Comment by johnpapa** [comment]
fixed in 1.4.1
