### ISSUE TITLE
light theme - cursor color overlapping with git changes tracking bar

### ISSUE THREAD

**Issue by manikawnth** [johnpapa/vscode-winteriscoming#37]
> ## Please provide us with the following information:

### Version

>1.3.0

### Repro steps

>Use light theme, commit a version to git, add some changes. You'll not be able to track the position of the cursor as the color of the git changes bar and the cursor are in the same blue color

### The log given by the failure.

>Not applicable

### Mention any other details that might be useful.
Refer to `line 24` of the screen shot below. There's a cursor hiding in the circle 

![image](https://user-images.githubusercontent.com/10106516/73214834-eda51780-4120-11ea-81fa-428f22d557c4.png)

> ---
>
> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment]
thanks.

fixed in 1.4.1
