### ISSUE TITLE
IntelliJ

### ISSUE THREAD

**Issue by nxm67420** [johnpapa/vscode-winteriscoming#38]
> ## Please provide us with the following information:
Can Someone Please Recreate This Theme For IntelliJ 😩. Im starting to use Intellij more often,  but this is my favorite theme ever!!
### Version

>

### Repro steps

>

### The log given by the failure.

>

### Mention any other details that might be useful.

> ---
>
> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment]
Thank for using it - sorry, cant help much with intellij
