### ISSUE TITLE
[1.3.1] Light theme editor shows text in italics

### ISSUE THREAD

**Issue by SferaDev** [johnpapa/vscode-winteriscoming#39]
If, and only if, this is a feature it should be configurable.

### Version

> 1.3.1

### Repro steps

> Open text editor

### The log given by the failure.

> N/A

### Mention any other details that might be useful.

Version 1.3:

![image](https://user-images.githubusercontent.com/2181866/76699944-95b37780-66b2-11ea-9e3f-64d951f26384.png)

Version 1.3.1:

![image](https://user-images.githubusercontent.com/2181866/76699954-a532c080-66b2-11ea-8056-5840fd89c0cb.png)

**Comment by kjarmicki** [comment]
I believe @johnpapa announced this option coming in 1.4.0 (ref: https://github.com/johnpapa/vscode-winteriscoming/issues/34#issuecomment-577326427). I found it quite unpleasant too, so for a quick-and-dirty hack, I replaced extension's theme file with the previous version.

**Comment by SferaDev** [comment]
> I believe @johnpapa announced this option coming in 1.4.0 (ref: [#34 (comment)](https://github.com/johnpapa/vscode-winteriscoming/issues/34#issuecomment-577326427)). I found it quite unpleasant too, so for a quick-and-dirty hack, I replaced extension's theme file with the previous version.

I installed the previos version too through the "Extensions" menu inside VSCode.

**Comment by kjarmicki** [comment]
Oh, so it is possible? :smile: I was looking for that option on the extension page, but now I see it's available under a gear icon from the list. This is clearly a better solution, thanks.

**Comment by johnpapa** [comment]
This is coming but I need to update the light theme first #35
