### ISSUE TITLE
my favourite theme is gone

### ISSUE THREAD

**Issue by liorJuice** [johnpapa/vscode-winteriscoming#41]
please enable old version of the light theme @.@

thanks.

**Comment by bbarao** [comment]
I also prefer the 1.3.0 version of the light theme.

**Comment by Luisetelo** [comment]
Same here!

**Comment by vierarb** [comment]
Please, roll back to the previous version. We are suffering! :(

**Comment by kalanda** [comment]
How dare you!

**Comment by skozz** [comment]
Life if enough hard with the coronavirus crisis, please give us back the old version ❤️

**Comment by liorJuice** [comment]
@bbarao @Luisetelo @vierarb @kalanda @skozz 

as a quick workaround just wanted to mention i found this 😉

<img width="481" alt="Screen Shot 2020-03-25 at 10 15 05" src="https://user-images.githubusercontent.com/45418456/77515684-a79ad480-6e81-11ea-858e-d9a2eed1443a.png">

**Comment by bbarao** [comment]
Thanks @liorJuice , I also downgraded the theme, but we shouldn't need to do that :(

**Comment by mpstv** [comment]
Hi everyone. 
I created a fork "Winter is coming" theme and called it "Winter is Light". This light theme based on "Winter is coming" (version 1.3). 
Also two modifications of the theme were made in addition - a completely italic version, and a version completely without italics. 
Theme is available on [github](https://github.com/mpstv/vscode-winterislight) and the [marketplace](https://marketplace.visualstudio.com/items?itemName=mpstv.winterislight).
If you want - you can use it.

**Comment by johnpapa** [comment]
I welcome a PR that modifies the light theme!

My requests:
1. show a before and after in the PR
2. modify the colors (removal has risks of other colors from other tools jumping in)
3. keep italics and non italics in synch with colors

**Comment by johnpapa** [comment]
#43 has been merged and published in 1.4.2

If more changes are desired, please open a new issue and identify what features you'd like changed.

thanks

**Comment by mpstv** [comment]
Hello everyone, after version 1.4.2 becomes available, I plan to unpublish my fork from marketplace and using Winter Is Coming instead.

**Comment by Luisetelo** [comment]
Thank you @johnpapa @mpstv!! really really appreciated 😍
