### ISSUE TITLE
High contrast elements in light theme

### ISSUE THREAD

**Issue by sergeysova** [johnpapa/vscode-winteriscoming#42]
Version 1.3.0
![image](https://user-images.githubusercontent.com/5620073/76738792-53ef0380-677c-11ea-9a8b-8301f4e1b926.png)

Version 1.4.0
![image](https://user-images.githubusercontent.com/5620073/76738854-6ff2a500-677c-11ea-9c84-b9bfb7b813c2.png)

Version 1.4.1
![image](https://user-images.githubusercontent.com/5620073/76738906-8436a200-677c-11ea-9b96-343311626672.png)

How can I disable those elements?

> I love the color scheme from 1.3.0 =(

**Comment by oieduardorabelo** [comment]
this is how it looks for me:

![Screen Shot 2020-03-19 at 12 09 07 AM](https://user-images.githubusercontent.com/829902/76954906-0a6a0880-6976-11ea-8061-9cb5b74eb233.png)

btw, many thanks for the theme, would be lovely to go back to 1.3 🎉

**Comment by johnpapa** [comment]
closing in favor of #41
