### ISSUE TITLE
Bring back comments old style (grey color with no italic)

### ISSUE THREAD

**Issue by bboulahdid** [johnpapa/vscode-winteriscoming#6]
Hi,

Can you please bring back the comments old style or at least a way to customize them?

I tried using `Custom CSS and JS Loader` with no result 😞 

Thank you in advance!

**Comment by johnpapa** [comment]
thanks for the feedback. the colors are being tweaked as i spend more time with this.

i am altering the comments back to gray.

the italics i'm keeping at this point.
