### ISSUE TITLE
Cannot load latest version (1.5)

### ISSUE THREAD

**Issue by jtsom** [johnpapa/vscode-winteriscoming#8]
> Please provide us with the following information:

### OS and Version?
> macOS (High Sierra)

### Versions
  >
Latest Insiders (b76a4a71434d6cdee69fa1d8bdc7533d09598d53)
Extension version 1.5

### Repro steps
  > Try to change to the new version and VSC does not switch.

### The log given by the failure.
>/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1325   ERR Unable to load /Users/john/.vscode-insiders/extensions/johnpapa.winteriscoming-0.5.0/themes/WinterIsComing-dark-color-theme.json: Problems parsing JSON theme file: Value expected: Error: Unable to load /Users/john/.vscode-insiders/extensions/johnpapa.winteriscoming-0.5.0/themes/WinterIsComing-dark-color-theme.json: Problems parsing JSON theme file: Value expected

**Comment by jtsom** [comment]
Line 228 has a comma at the end.

**Comment by kriscoleman** [comment]
Thanks for finding the culprit jtsom. I created a pull request to fix this issue.

**Comment by jtsom** [comment]
Yeah after I posted all that I realized I should have just done that too! Thanks!

**Comment by kriscoleman** [comment]
Happy to help! you did most of the work ;)
